language: java
install: true
jdk:
- oraclejdk8

script:
- ./gradlew build

after_success:
- ./gradlew test jacocoTestReport 
- bash <(curl -s https://codecov.io/bash)

before_install:
- chmod +x ./gradlew
- openssl aes-256-cbc -K $encrypted_451ce9a88da3_key -iv $encrypted_451ce9a88da3_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv test.application.properties src/test/resources/application.properties
- mv application.properties src/main/resources/application.properties
